/**
 * Public drift reports, generated by scripts/generate-reports.mjs into
 * src/data/reports/*.json and built into /reports/<owner>/<repo>.
 */
export interface Report {
  repo: string;
  owner: string;
  name: string;
  description: string | null;
  stars: number;
  homepage: string | null;
  language: string | null;
  defaultBranch: string;
  commit: string;
  generatedAt: string;
  /** null when Buoy found too few components to judge (see MIN_SCORABLE_COMPONENTS in core). */
  score: number | null;
  tier: string;
  pillars: Record<string, { score: number; max: number }>;
  metrics: Record<string, unknown> & {
    componentCount: number;
    tokenCount: number;
    hardcodedValueCount: number;
    vendoredDriftCount?: number;
    unusedComponentCount: number;
    repeatedPatternCount: number;
    detectedFrameworkNames: string[];
    topHardcodedColor?: { value: string; count: number } | null;
    worstFile?: { path: string; issueCount: number } | null;
  };
  suggestions: string[];
  /** Points each short pillar is missing and the change that earns them (CLI 0.8.4+). */
  pathTo100?: Array<{ pillar: string; points: number; action: string }>;
  /** Values the code marks as deliberate (CLI 0.8.6+): left out of findings and the score. */
  noted?: {
    count: number;
    byKind: Record<string, number>;
    samples: Array<{ file: string; line: number; value: string; kind: string; reason: string }>;
  } | null;
  driftSummary: { total: number; critical: number; warning: number; info: number };
  driftByType: Record<string, number>;
  topColors: Array<{ value: string; count: number }>;
  topSpacing: Array<{ value: string; count: number }>;
  worstFiles: Array<{ file: string; count: number }>;
  samples: Array<{ component: string; location: string; entries: string[] }>;
  scanSeconds: number;
}

const files = import.meta.glob<Report>('../data/reports/*.json', { eager: true, import: 'default' });

// A repo with almost no components found is a scanner coverage gap, not a
// verdict on the project; keep those off the public pages.
const MIN_COMPONENTS = 20;

export function allReports(): Report[] {
  return Object.values(files)
    .filter((r) => r.metrics.componentCount >= MIN_COMPONENTS && r.score !== null)
    .sort((a, b) => b.stars - a.stars);
}

export function scoreColor(score: number | null): string {
  if (score === null) return 'text-slate';
  return score >= 80 ? 'text-success' : score >= 60 ? 'text-sunrise' : 'text-red-400';
}

export function scoreBg(score: number | null): string {
  if (score === null) return 'bg-slate';
  return score >= 80 ? 'bg-success' : score >= 60 ? 'bg-sunrise' : 'bg-red-400';
}

export function formatStars(n: number): string {
  return n >= 1000 ? `${(n / 1000).toFixed(n >= 10000 ? 0 : 1)}k` : String(n);
}

export function fileUrl(report: Report, location: string): string {
  const [path, line] = location.split(':');
  return `https://github.com/${report.repo}/blob/${report.commit}/${path}${line ? `#L${line}` : ''}`;
}

/** `#FFF`, `#fff` and `#ffffff` are one colour; merge them before display. */
export function mergeColors(values: Array<{ value: string; count: number }>): Array<{ value: string; count: number }> {
  const merged = new Map<string, number>();
  for (const { value, count } of values) {
    let key = value.trim().toLowerCase();
    const short = /^#([0-9a-f])([0-9a-f])([0-9a-f])$/.exec(key);
    if (short) key = `#${short[1]}${short[1]}${short[2]}${short[2]}${short[3]}${short[3]}`;
    merged.set(key, (merged.get(key) ?? 0) + count);
  }
  return [...merged.entries()].sort((a, b) => b[1] - a[1]).map(([value, count]) => ({ value, count }));
}

/** schema.org structured data for a report page (search engines and AI answer engines read this). */
export function reportJsonLd(r: Report, path: string): Record<string, unknown> {
  const vendored = r.metrics.vendoredDriftCount ?? 0
  const findings = Math.max(0, r.metrics.hardcodedValueCount - vendored)
  return {
    '@context': 'https://schema.org',
    '@type': 'Report',
    name: `${r.repo} design system health report`,
    headline: `${r.repo}: design health ${r.score ?? 'N/A'}/100`,
    description: `Design health ${r.score ?? 'N/A'}/100 (${r.tier}) for ${r.repo}: ${findings} hardcoded-value findings across ${r.metrics.componentCount} components and ${r.metrics.tokenCount} design tokens, scanned by Buoy.`,
    url: `https://buoy.design${path}`,
    datePublished: r.generatedAt,
    dateModified: r.generatedAt,
    author: { '@type': 'Organization', name: 'Buoy', url: 'https://buoy.design' },
    publisher: { '@type': 'Organization', name: 'Buoy', url: 'https://buoy.design' },
    about: {
      '@type': 'SoftwareSourceCode',
      name: r.repo,
      codeRepository: `https://github.com/${r.repo}`,
      ...(r.language ? { programmingLanguage: r.language } : {}),
    },
    isBasedOn: { '@type': 'SoftwareApplication', name: 'Buoy CLI', url: 'https://www.npmjs.com/package/@buoy-design/cli', softwareVersion: r.cliVersion },
  }
}

/** Aggregate numbers across the public reports, computed at build time so guides quote current data. */
export function reportStats() {
  const reports = allReports()
  const scored = reports.filter((r) => r.score !== null)
  const scores = scored.map((r) => r.score as number).sort((a, b) => a - b)
  const own = (r: Report) => Math.max(0, r.metrics.hardcodedValueCount - (r.metrics.vendoredDriftCount ?? 0))
  const mid = Math.floor(scores.length / 2)
  const median = scores.length === 0 ? 0 : scores.length % 2 ? scores[mid]! : Math.round((scores[mid - 1]! + scores[mid]!) / 2)
  return {
    repoCount: reports.length,
    scoredCount: scored.length,
    medianScore: median,
    minScore: scores[0] ?? 0,
    maxScore: scores[scores.length - 1] ?? 0,
    greatCount: scores.filter((s) => s >= 80).length,
    findings: scored.reduce((n, r) => n + own(r), 0),
    components: scored.reduce((n, r) => n + r.metrics.componentCount, 0),
    tokens: scored.reduce((n, r) => n + r.metrics.tokenCount, 0),
    noted: scored.reduce((n, r) => n + (r.noted?.count ?? 0), 0),
    best: [...scored].sort((a, b) => (b.score as number) - (a.score as number)).slice(0, 3),
    updated: reports.map((r) => r.generatedAt).sort().pop()?.slice(0, 10) ?? '',
  }
}
