/**
 * Public drift reports, generated by scripts/generate-reports.mjs into
 * src/data/reports/*.json and built into /reports/<owner>/<repo>.
 */
export interface Report {
  repo: string;
  owner: string;
  name: string;
  description: string | null;
  stars: number;
  homepage: string | null;
  language: string | null;
  defaultBranch: string;
  commit: string;
  generatedAt: string;
  /** null when Buoy found too few components to judge (see MIN_SCORABLE_COMPONENTS in core). */
  score: number | null;
  tier: string;
  pillars: Record<string, { score: number; max: number }>;
  metrics: Record<string, unknown> & {
    componentCount: number;
    tokenCount: number;
    hardcodedValueCount: number;
    vendoredDriftCount?: number;
    unusedComponentCount: number;
    repeatedPatternCount: number;
    detectedFrameworkNames: string[];
    topHardcodedColor?: { value: string; count: number } | null;
    worstFile?: { path: string; issueCount: number } | null;
  };
  suggestions: string[];
  /** Points each short pillar is missing and the change that earns them (CLI 0.8.4+). */
  pathTo100?: Array<{ pillar: string; points: number; action: string }>;
  /** Values the code marks as deliberate (CLI 0.8.6+): left out of findings and the score. */
  noted?: {
    count: number;
    byKind: Record<string, number>;
    samples: Array<{ file: string; line: number; value: string; kind: string; reason: string }>;
  } | null;
  driftSummary: { total: number; critical: number; warning: number; info: number };
  driftByType: Record<string, number>;
  topColors: Array<{ value: string; count: number }>;
  topSpacing: Array<{ value: string; count: number }>;
  worstFiles: Array<{ file: string; count: number }>;
  samples: Array<{ component: string; location: string; entries: string[] }>;
  scanSeconds: number;
}

const files = import.meta.glob<Report>('../data/reports/*.json', { eager: true, import: 'default' });

// A repo with almost no components found is a scanner coverage gap, not a
// verdict on the project; keep those off the public pages.
const MIN_COMPONENTS = 20;

export function allReports(): Report[] {
  return Object.values(files)
    .filter((r) => r.metrics.componentCount >= MIN_COMPONENTS && r.score !== null)
    .sort((a, b) => b.stars - a.stars);
}

export function scoreColor(score: number | null): string {
  if (score === null) return 'text-slate';
  return score >= 80 ? 'text-success' : score >= 60 ? 'text-sunrise' : 'text-red-400';
}

export function scoreBg(score: number | null): string {
  if (score === null) return 'bg-slate';
  return score >= 80 ? 'bg-success' : score >= 60 ? 'bg-sunrise' : 'bg-red-400';
}

export function formatStars(n: number): string {
  return n >= 1000 ? `${(n / 1000).toFixed(n >= 10000 ? 0 : 1)}k` : String(n);
}

export function fileUrl(report: Report, location: string): string {
  const [path, line] = location.split(':');
  return `https://github.com/${report.repo}/blob/${report.commit}/${path}${line ? `#L${line}` : ''}`;
}

/** `#FFF`, `#fff` and `#ffffff` are one colour; merge them before display. */
export function mergeColors(values: Array<{ value: string; count: number }>): Array<{ value: string; count: number }> {
  const merged = new Map<string, number>();
  for (const { value, count } of values) {
    let key = value.trim().toLowerCase();
    const short = /^#([0-9a-f])([0-9a-f])([0-9a-f])$/.exec(key);
    if (short) key = `#${short[1]}${short[1]}${short[2]}${short[2]}${short[3]}${short[3]}`;
    merged.set(key, (merged.get(key) ?? 0) + count);
  }
  return [...merged.entries()].sort((a, b) => b[1] - a[1]).map(([value, count]) => ({ value, count }));
}
